export const SEARCH_BOOKS = 'SEARCH_BOOKS';
export const SEARCH_LOADING = 'SEARCH_LOADING';
export const BOOK_DETAILS = "BOOK_DETAILS";
export const DETAILS_LOADING = "DETAILS_LOADING"
export const ADD_FAVOURITE = "ADD_FAVOURITE";
export const REMOVE_FAVOURITE = "REMOVE_FAVOURITE";
export const GET_FAVOURITE = "GET_FAVOURITE";


